### ISSUE TITLE
My version

### ISSUE THREAD

**Issue by omBratteng** [edmundojr/localhost#1]
Here's my version, had it like this for a few years now.
I control the listings in a separate document, because I have so many different experiments there. But I also got the possibility to list everything in my localhost folder.
![My Localhost](http://i.imgur.com/90nVSQ3.jpg)

**Comment by manfromanotherland** [comment]
That's nice, @tnViking, thanks for sharing!

Do you have a repository of the project? Hit me with the link, I'm thinking of adding an “Alternatives” section on the README, so people can see the different approaches :D

**Comment by omBratteng** [comment]
I don't have a repo of it yet, but I'll clean up the code and post a repo link here
