### ISSUE TITLE
Wrong name

### ISSUE THREAD

**Issue by fregante** [edmundojr/localhost#2]
"localhost" has nothing to do with this feature, which is a directory index.

**Comment by fregante** [comment]
Also as a feature-packed and mature alternative, here's h5ai: https://larsjung.de/h5ai/ and https://larsjung.de/h5ai/demo/

**Comment by manfromanotherland** [comment]
Right on spot here, @bfred-it. Localhost it's just the way I choose to name the project, but I've added some clarification on the README file, in case anyone was confused.

Also, that alternative you shared is amazing! Thanks :D

**Comment by manfromanotherland** [comment]
Hello again, @bfred-it. I add your suggestion on the README file. Thanks again ;)

**Comment by fregante** [comment]
:+1:
